version: '3.8'
services:
    proxy:
        container_name: proxy  # set container name, so it can easily identified while using docker commands
        hostname: proxy # set the host name, so it can be easily referred to in our service
        image: nginx:alpine # grab the alpine version of nginx
        volumes: # add the configuration file to the container
            - ./configuration/nginx.conf:/etc/nginx/nginx.conf
        ports: # expose local port 80 to port 80
            - 80:80
        networks: # in the network service so it can access the other two services
            - service
        tty: true # 
    
    url_shortener_service:
        container_name: url_shortener_service
        hostname: url_shortener_service
        restart: unless-stopped
        build: 
            context: ./url_shortener_service
            target: production_stage
        image: alexantonides/wscbs-url-shortener-service
        volumes:
            - ./url_shortener_service:/app
        networks:
            - service
        environment:
            - FLASK_ENV=development

    user_service:
        container_name: user_service
        hostname: user_service
        restart: unless-stopped
        build: 
            context: ./user_service
            target: production_stage
        image: alexantonides/wscbs-user-service
        volumes:
            - ./user_service:/app
        networks:
            - service
        environment:
            - FLASK_ENV=development

networks:
    service: