apiVersion: apps/v1
kind: Deployment
metadata:
  name: url_shortener_service-deployment
spec:
  selector:
    matchLabels:
      app: url_shortener_service
  replicas: 3
  template:
    metadata:
      labels:
        app: url_shortener_service
    spec:
      containers:
      - name: url_shortener_service
        image: url_shortener_service
        ports:
        - containerPort: 5000
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service-deployment
spec:
  selector:
    matchLabels:
      app: user_service
  replicas: 3
  template:
    metadata:
      labels:
        app: user_service
    spec:
      containers:
      - name: user_service
        image: user_service
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc