apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    run: url-shortener-service
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: url-shortener-service