apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    run: url-shortener-service
spec:
  type: NodePort
  selector:
    run: url-shortener-service
  ports:
  - port: 5000
    targetPort: 5000
  externalIPs:
    - 145.100.134.49