apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    run: user-service
spec:
  type: NodePort
  selector:
    app: user-service-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service-deployment
  template:
    metadata:
      labels:
        app: user-service-deployment
    spec:
      containers:
      - name: wscbs-user-service
        image: alexantonides/wscbs-user-service