apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    run: user-service
spec:
  type: NodePort
  selector:
    run: user-service 
  ports:
  - port: 5001
    targetPort: 5000
  externalIPs:
    - 145.100.134.49